version: '3.5'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file: 
      - .env
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: unless-stopped
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mal/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mal/data/wordpress'

networks:
  inception:
    driver: bridge
